import type { Metadata } from "next";
import { ReduxProvider } from "./providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import Header from "@/layouts/common/Header";
import { SplitterProvider } from "@/contexts/SplitterContext";

// ========= Plugins SCSS =========
import "antd/dist/reset.css";
import "../styles/scss/styles.scss";
// ========= Plugins CSS =========
import "./globals.css";
import Body from "@/layouts/common/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SplitterProvider>
          <AntdRegistry>
            <ReduxProvider>
              <header>
                <Header />
              </header>
              <main>
                <Body>{children}</Body>
              </main>
            </ReduxProvider>
          </AntdRegistry>
        </SplitterProvider>
      </body>
    </html>
  );
}
