import type { Metadata } from "next";
import { ReduxProvider } from "./providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "@/layouts/common/Header";

// ========= Plugins SCSS =========
import "antd/dist/reset.css";
import "../styles/scss/styles.scss";
// ========= Plugins CSS =========
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AntdRegistry>
          <ReduxProvider>
            <header><Header/></header>
            <main>{children}</main>
          </ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
